# Simplified Patching Tool Configuration

# Workflow settings
name: "Pre-Patch Workflow"

# Landing zones to process
landing_zones:
  - "lz250nonprod"
  - "cmsnonprod"
  - "fotoolspreprod"

# Basic AWS settings
aws:
  region: "ap-southeast-2"
  role_name: "HIPCMSProvisionSpokeRole"
  timeout: 60
  max_retries: 3

# Phase settings
scanner:
  enabled: true
  timeout_minutes: 30
  max_concurrent: 10
  retry_attempts: 2

ami_backup:
  enabled: true
  timeout_minutes: 60
  max_concurrent: 5
  retry_attempts: 2

server_manager:
  enabled: true
  timeout_minutes: 10
  max_concurrent: 10
  retry_attempts: 2

# Output settings
output_dir: "reports"
log_level: "INFO"

# Execution options
skip_backup: false
skip_validation: false
continue_on_error: true
